name: agentic-finance
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - yfinance
  - matplotlib
  - pandas
  - requests
  - python-dotenv
  - plotly
  - pip
  - pip:
      - streamlit
      - openai
      - beautifulsoup4
      - PyPDF2

